# Site settings
title: Github_Blog
SEOTitle: Pluto-C137 博客
header-img: img/post-bg-desk.jpg
email: ssrzz@pm.me
description: "May the force be with you"
keyword: "BY, BY Blog, Linux, Python, C++, AI, ML"
url: "http://ssrzz.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ssrzz/ssrzz.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "work hard, work smart"
sidebar-avatar: /img/avatar_pikaqiu.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     None
github_username:    ssrzz
facebook_username:  None
jianshu_username:   None




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: ssrzz
# url: http://ssrzz.github.io


# comments_provider: gitalk
# Gitalk
gitalk:
  enable: true      #是否开启Gitalk评论
  clientID: ff0780c2422d2030dcb7                            #生成的clientID
  clientSecret: 485da2c930c535b6b612b776f3202ca7e1d392a3    #生成的clientSecret
  repo: ssrzz.github.io    #仓库名称
  owner: ssrzz    #github用户名
  admin: ssrzz
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  labels: ['Gitalk'] 
  id:



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
